name: Laravel Package Github Workflow Sync

on:
  push:
    branches:
      - main
env:
  DRY_RUN: false
  RETRY_MODE: true
  REPOSITORIES: |
    fuelviews/laravel-cpanel-auto-deploy@main
    fuelviews/laravel-sitemap@main
    fuelviews/laravel-robots-txt@main
    fuelviews/laravel-vite@main
    fuelviews/laravel-cloudflare-cache@main
    fuelviews/laravel-tailwindcss@main
    fuelviews/laravel-form@main
    fuelviews/laravel-middleware@main
    fuelviews/laravel-navigation@main
    fuelviews/laravel-init@main
  
  WORKFLOW_FILES: |
    laravel-package/workflows/open-ai-pr-description.yml=.github/workflows/open-ai-pr-description.yml
    laravel-package/workflows/auto-release.yml=.github/workflows/auto-release.yml
    laravel-package/workflows/fix-php-code-style-issues.yml=.github/workflows/fix-php-code-style-issues.yml
    laravel-package/workflows/update-changelog.yml=.github/workflows/update-changelog.yml
    laravel-package/workflows/dependabot-auto-merge.yml=.github/workflows/dependabot-auto-merge.yml
    laravel-package/workflows/run-tests.yml=.github/workflows/run-tests.yml
    laravel-package/issue_template/bug.yml=.github/ISSUE_TEMPLATE/bug.yml
    laravel-package/dependabot.yml=.github/dependabot.yml
    laravel-package/funding.yml=.github/funding.yml

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
